### ISSUE TITLE
运行失败~

### ISSUE THREAD

**Issue by dadaa1** [GivingWu/imooc-net-crawler#1]
rt

**Comment by givingwu** [comment]
运行失败？请给出具体的错误内容，谢谢。

**Comment by dadaa1** [comment]
![image](https://user-images.githubusercontent.com/12947361/30510847-231c3670-9aff-11e7-9adc-02e244863678.png)

**Comment by givingwu** [comment]
抱歉，回复您晚了。我的建议是，请您更新 npm 和 node 版本。然后执行下列脚本：

```bash
    npm uninstall
```
```bash
    npm install 
```

try again.
